### PR TITLE
Added support for right/left join

### PR DESCRIPTION
**Pull request by foikila**

### CODE REVIEW

**Comment by xt9** [comment]
Not DRY enough

**Comment by foikila** [comment]
True true. Will fix

**Comment by mosbth** [comment]
Can we se a testcase/usecase for it somewhere here:
https://github.com/mosbth/cdatabase/blob/master/webroot/testSQLQueryBuilderBasic.php#L137-L157

**Comment by foikila** [comment]
Unittest added and testcase/usecase like in https://github.com/mosbth/cdatabase/blob/master/webroot/testSQLQueryBuilderBasic.php

**Comment by foikila** [comment]
Build failed because that I am testing the database with mysqldb and I can't connect to travis mysqldb. Testing with sqlite should fix this.

**Comment by mosbth** [comment]
Now we have support for LEFT | RIGHT OUTER JOIN, nice.

**Pull request merged**
